# Generated by Django 4.1.7 on 2023-04-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alcohol",
            old_name="marca",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="combination",
            old_name="barreja",
            new_name="mix",
        ),
        migrations.RenameField(
            model_name="mix",
            old_name="marca",
            new_name="brand",
        ),
    ]
