# Generated by Django 4.1.7 on 2023-04-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_rename_marca_alcohol_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="type",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "Alcohol"), (2, "Mix")], default=0
            ),
        ),
    ]
